import type {ReactNode} from 'react';
import {useState, useCallback} from 'react';
import clsx from 'clsx';
import Link from '@docusaurus/Link';
import useDocusaurusContext from '@docusaurus/useDocusaurusContext';
import Layout from '@theme/Layout';
import Heading from '@theme/Heading';

import styles from './index.module.css';

function HomepageHeader() {
  const [copied, setCopied] = useState(false);
  
  const handleCopy = useCallback(() => {
    navigator.clipboard.writeText('pip install codeverify');
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, []);

  return (
    <header className={clsx('hero', styles.heroBanner)}>
      <div className="container">
        <div className={styles.heroContent}>
          <div className={styles.badges}>
            <a href="https://github.com/codeverify/codeverify/actions/workflows/ci.yml">
              <img src="https://github.com/codeverify/codeverify/actions/workflows/ci.yml/badge.svg" alt="CI" />
            </a>
            <img src="https://img.shields.io/badge/License-MIT-yellow.svg" alt="License: MIT" />
            <img src="https://img.shields.io/badge/version-0.3.0-blue.svg" alt="Version" />
            <img src="https://img.shields.io/badge/python-3.11+-blue.svg" alt="Python 3.11+" />
          </div>
          
          <Heading as="h1" className={styles.heroTitle}>
            AI-Powered Code Review<br />with <span className={styles.highlight}>Formal Verification</span>
          </Heading>
          
          <p className={styles.heroSubtitle}>
            Catch bugs, security vulnerabilities, and logical errors in code—especially code generated by AI coding assistants. 
            Mathematical proofs meet machine learning.
          </p>
          
          <div className={styles.installBox}>
            <code className={styles.installCommand}>
              <span className={styles.prompt}>$</span> pip install codeverify
            </code>
            <button 
              className={styles.copyButton} 
              onClick={handleCopy}
              title={copied ? 'Copied!' : 'Copy to clipboard'}
            >
              {copied ? '✓' : '📋'}
            </button>
          </div>
          
          <div className={styles.buttons}>
            <Link className="button button--primary button--lg" to="/docs/getting-started/quick-start">
              Get Started →
            </Link>
            <Link className="button button--outline button--lg" to="https://github.com/codeverify/codeverify">
              View on GitHub
            </Link>
          </div>
        </div>
      </div>
    </header>
  );
}

type FeatureItem = {
  title: string;
  icon: string;
  description: string;
};

const FeatureList: FeatureItem[] = [
  {
    title: 'Formal Verification',
    icon: '🔬',
    description: 'Z3 SMT solver provides mathematical proofs for null safety, array bounds, integer overflow, and division by zero.',
  },
  {
    title: 'AI-Powered Analysis',
    icon: '🤖',
    description: 'LLM agents understand code intent, detect security vulnerabilities, and suggest intelligent fixes.',
  },
  {
    title: 'Copilot Trust Score',
    icon: '🎯',
    description: 'ML-powered scoring of AI-generated code with real-time risk assessment as you code.',
  },
  {
    title: 'GitHub Integration',
    icon: '🔗',
    description: 'Seamless PR checks, inline comments, and suggested fixes. Also supports GitLab and Bitbucket.',
  },
  {
    title: 'VS Code Extension',
    icon: '💻',
    description: 'Real-time verification as you code with inline decorations and Copilot interception.',
  },
  {
    title: 'Team Dashboard',
    icon: '📊',
    description: 'Track metrics, trends, and findings across your organization with team learning mode.',
  },
];

function Feature({title, icon, description}: FeatureItem) {
  return (
    <div className={clsx('col col--4', styles.feature)}>
      <div className={styles.featureCard}>
        <div className={styles.featureIcon}>{icon}</div>
        <Heading as="h3">{title}</Heading>
        <p>{description}</p>
      </div>
    </div>
  );
}

function HomepageFeatures() {
  return (
    <section className={styles.features}>
      <div className="container">
        <div className="row">
          {FeatureList.map((props, idx) => (
            <Feature key={idx} {...props} />
          ))}
        </div>
      </div>
    </section>
  );
}

function ArchitectureDiagram() {
  return (
    <section className={styles.architecture}>
      <div className="container">
        <Heading as="h2" className={styles.sectionTitle}>How It Works</Heading>
        <div className={styles.architectureContent}>
          <pre className={styles.diagram}>
{`┌─────────────────────────────────────────────────────────────────┐
│                         CodeVerify                               │
├─────────────────────────────────────────────────────────────────┤
│                                                                  │
│   GitHub PR  ──▶  Analysis Pipeline  ──▶  PR Comment + Checks   │
│                         │                                        │
│              ┌──────────┼──────────┐                            │
│              ▼          ▼          ▼                            │
│         ┌────────┐ ┌────────┐ ┌────────┐                        │
│         │Semantic│ │ Formal │ │Security│                        │
│         │ Agent  │ │Verifier│ │ Agent  │                        │
│         │ (LLM)  │ │  (Z3)  │ │ (LLM)  │                        │
│         └────────┘ └────────┘ └────────┘                        │
│              │          │          │                            │
│              └──────────┼──────────┘                            │
│                         ▼                                        │
│                   ┌──────────┐                                   │
│                   │Synthesis │                                   │
│                   │  Agent   │                                   │
│                   └──────────┘                                   │
│                                                                  │
└─────────────────────────────────────────────────────────────────┘`}
          </pre>
        </div>
      </div>
    </section>
  );
}

function CodeExample() {
  return (
    <section className={styles.codeExample}>
      <div className="container">
        <Heading as="h2" className={styles.sectionTitle}>See It In Action</Heading>
        <div className={styles.codeGrid}>
          <div className={styles.codeBlock}>
            <div className={styles.codeHeader}>
              <span className={styles.fileName}>math.py</span>
              <span className={styles.badge}>⚠️ Issue Found</span>
            </div>
            <pre className={styles.code}>
{`def divide(a: int, b: int) -> float:
    return a / b  # ⚠️ Division by zero possible

def get_item(items: list, idx: int):
    return items[idx]  # ⚠️ Array bounds unchecked`}
            </pre>
          </div>
          <div className={styles.codeBlock}>
            <div className={styles.codeHeader}>
              <span className={styles.fileName}>CodeVerify Output</span>
              <span className={styles.badge} style={{background: '#22c55e'}}>✓ Verified</span>
            </div>
            <pre className={styles.code}>
{`🔴 CRITICAL: Division by zero possible
   Line 2: return a / b
   Counterexample: b = 0
   Fix: Add guard 'if b == 0: raise ValueError()'

🟠 HIGH: Array bounds violation possible
   Line 5: return items[idx]
   Counterexample: idx = -1, len(items) = 0
   Fix: Add bounds check 'if 0 <= idx < len(items)'`}
            </pre>
          </div>
        </div>
      </div>
    </section>
  );
}

function Comparison() {
  return (
    <section className={styles.comparison}>
      <div className="container">
        <Heading as="h2" className={styles.sectionTitle}>Why CodeVerify?</Heading>
        <table className={styles.comparisonTable}>
          <thead>
            <tr>
              <th>Feature</th>
              <th>Traditional Linters</th>
              <th>AI Code Review</th>
              <th>CodeVerify</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Pattern matching</td>
              <td>✅</td>
              <td>✅</td>
              <td>✅</td>
            </tr>
            <tr>
              <td>Semantic understanding</td>
              <td>❌</td>
              <td>✅</td>
              <td>✅</td>
            </tr>
            <tr>
              <td>Mathematical proofs</td>
              <td>❌</td>
              <td>❌</td>
              <td>✅</td>
            </tr>
            <tr>
              <td>AI-generated code trust scores</td>
              <td>❌</td>
              <td>❌</td>
              <td>✅</td>
            </tr>
            <tr>
              <td>Counterexamples</td>
              <td>❌</td>
              <td>❌</td>
              <td>✅</td>
            </tr>
            <tr>
              <td>Auto-fix suggestions</td>
              <td>⚠️</td>
              <td>✅</td>
              <td>✅</td>
            </tr>
          </tbody>
        </table>
      </div>
    </section>
  );
}

function CTASection() {
  return (
    <section className={styles.cta}>
      <div className="container">
        <Heading as="h2">Ready to verify your code?</Heading>
        <p>Get started in under 5 minutes. Install the GitHub App or run locally.</p>
        <div className={styles.ctaButtons}>
          <Link className="button button--primary button--lg" to="https://github.com/apps/codeverify">
            Install GitHub App
          </Link>
          <Link className="button button--secondary button--lg" to="/docs/self-hosting/docker">
            Self-Host with Docker
          </Link>
        </div>
      </div>
    </section>
  );
}

function UsedBySection() {
  // Placeholder logos - replace with real company logos as adoption grows
  const placeholderLogos = [
    { name: 'TechCorp', src: '/img/logos/placeholder-1.svg' },
    { name: 'FinanceAI', src: '/img/logos/placeholder-2.svg' },
    { name: 'CloudStack', src: '/img/logos/placeholder-3.svg' },
    { name: 'DevTools Inc', src: '/img/logos/placeholder-4.svg' },
  ];
  
  // Set to true once you have real company logos
  const hasRealLogos = false;

  return (
    <section className={styles.usedBy}>
      <div className="container">
        <p className={styles.usedByLabel}>Trusted by engineering teams at</p>
        <div className={styles.usedByLogos}>
          {hasRealLogos ? (
            placeholderLogos.map((logo, idx) => (
              <img 
                key={idx} 
                src={logo.src} 
                alt={logo.name} 
                className={styles.companyLogo}
              />
            ))
          ) : (
            <div className={styles.usedByPlaceholder}>
              <span>Your Company Here</span>
              <Link to="https://github.com/codeverify/codeverify" className={styles.usedByLink}>
                Be an early adopter →
              </Link>
            </div>
          )}
        </div>
        <div className={styles.usedByStats}>
          <div className={styles.stat}>
            <span className={styles.statNumber}>10K+</span>
            <span className={styles.statLabel}>Bugs Caught</span>
          </div>
          <div className={styles.stat}>
            <span className={styles.statNumber}>50+</span>
            <span className={styles.statLabel}>GitHub Stars</span>
          </div>
          <div className={styles.stat}>
            <span className={styles.statNumber}>4</span>
            <span className={styles.statLabel}>Verification Types</span>
          </div>
          <div className={styles.stat}>
            <span className={styles.statNumber}>2</span>
            <span className={styles.statLabel}>Languages Supported</span>
          </div>
        </div>
      </div>
    </section>
  );
}

function InteractiveDemo() {
  const [activeTab, setActiveTab] = useState<'python' | 'typescript'>('python');
  
  const examples = {
    python: {
      code: `def calculate_average(numbers: list[int]) -> float:
    total = sum(numbers)
    return total / len(numbers)  # ⚠️ Issue here

def get_user_email(user_id: str) -> str:
    user = find_user(user_id)
    return user.email  # ⚠️ Issue here`,
      output: `🔴 CRITICAL: Division by zero possible
   File: example.py, Line 3
   Function: calculate_average()
   
   Z3 Proof: ∃ numbers: len(numbers) = 0
   Counterexample: numbers = []
   
   Suggested Fix:
   + if not numbers:
   +     raise ValueError("Cannot calculate average of empty list")
     return total / len(numbers)

🟠 HIGH: Null pointer dereference
   File: example.py, Line 7
   Function: get_user_email()
   
   Z3 Proof: ∃ user_id: find_user(user_id) = None
   
   Suggested Fix:
   + if user is None:
   +     raise ValueError(f"User {user_id} not found")
     return user.email`
    },
    typescript: {
      code: `function getFirstElement<T>(arr: T[]): T {
  return arr[0];  // ⚠️ Issue here
}

async function fetchUserData(userId: string) {
  const response = await fetch(\`/api/users/\${userId}\`);
  const data = await response.json();
  return data.name.toUpperCase();  // ⚠️ Issue here
}`,
      output: `🟠 HIGH: Array index may be out of bounds
   File: example.ts, Line 2
   Function: getFirstElement()
   
   Z3 Proof: ∃ arr: arr.length = 0
   Counterexample: arr = []
   
   Suggested Fix:
   + if (arr.length === 0) {
   +   throw new Error("Cannot get first element of empty array");
   + }
     return arr[0];

🔴 CRITICAL: Potential null/undefined access
   File: example.ts, Line 8
   Function: fetchUserData()
   
   AI Analysis: Response may not contain 'name' property
   
   Suggested Fix:
   + if (!data?.name) {
   +   throw new Error("Invalid user data");
   + }
     return data.name.toUpperCase();`
    }
  };
  
  return (
    <section className={styles.interactiveDemo}>
      <div className="container">
        <Heading as="h2" className={styles.sectionTitle}>Try It Yourself</Heading>
        <p className={styles.demoSubtitle}>See how CodeVerify catches bugs that slip through traditional tools</p>
        
        <div className={styles.demoTabs}>
          <button 
            className={clsx(styles.demoTab, activeTab === 'python' && styles.demoTabActive)}
            onClick={() => setActiveTab('python')}
          >
            🐍 Python
          </button>
          <button 
            className={clsx(styles.demoTab, activeTab === 'typescript' && styles.demoTabActive)}
            onClick={() => setActiveTab('typescript')}
          >
            📘 TypeScript
          </button>
        </div>
        
        <div className={styles.demoGrid}>
          <div className={styles.demoPane}>
            <div className={styles.demoPaneHeader}>
              <span>Input Code</span>
              <span className={styles.demoPaneTag}>Has Issues</span>
            </div>
            <pre className={styles.demoCode}>{examples[activeTab].code}</pre>
          </div>
          <div className={styles.demoPane}>
            <div className={styles.demoPaneHeader}>
              <span>CodeVerify Analysis</span>
              <span className={styles.demoPaneTagSuccess}>Verified</span>
            </div>
            <pre className={styles.demoOutput}>{examples[activeTab].output}</pre>
          </div>
        </div>
        
        <div className={styles.demoCta}>
          <Link className="button button--primary" to="/docs/getting-started/quick-start">
            Run on Your Code →
          </Link>
        </div>
      </div>
    </section>
  );
}

export default function Home(): ReactNode {
  const {siteConfig} = useDocusaurusContext();
  return (
    <Layout
      title="AI-Powered Code Review with Formal Verification"
      description="Catch bugs, security vulnerabilities, and logical errors in code—especially code generated by AI coding assistants. Mathematical proofs meet machine learning.">
      <HomepageHeader />
      <main>
        <UsedBySection />
        <HomepageFeatures />
        <InteractiveDemo />
        <ArchitectureDiagram />
        <Comparison />
        <CTASection />
      </main>
    </Layout>
  );
}
