"""GitHub Marketplace & One-Click Install.

Provides GitHub Marketplace listing management, one-click installation,
automatic configuration generation, and free-tier metering for
seamless CodeVerify onboarding.

Features:
- GitHub Marketplace listing metadata and pricing tiers
- One-click install flow with automatic repo configuration
- Free-tier usage metering and enforcement
- GitHub Actions workflow template generation
- Installation analytics and tracking
"""

from __future__ import annotations

import hashlib
import secrets
import uuid
from collections import defaultdict
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any

import structlog

logger = structlog.get_logger()


class MarketplacePlan(str, Enum):
    """Pricing plans available on GitHub Marketplace."""

    FREE = "free"
    PRO = "pro"
    TEAM = "team"
    ENTERPRISE = "enterprise"


class InstallationStatus(str, Enum):
    """Status of a GitHub App installation."""

    PENDING = "pending"
    ACTIVE = "active"
    SUSPENDED = "suspended"
    UNINSTALLED = "uninstalled"


class OnboardingPhase(str, Enum):
    """Phases of the one-click install flow."""

    APP_INSTALLED = "app_installed"
    CONFIG_GENERATED = "config_generated"
    WORKFLOW_CREATED = "workflow_created"
    BASELINE_SCAN_QUEUED = "baseline_scan_queued"
    ONBOARDING_COMPLETE = "onboarding_complete"


class UsageMetric(str, Enum):
    """Tracked usage metrics for metering."""

    VERIFICATIONS = "verifications"
    AI_ANALYSES = "ai_analyses"
    PR_REVIEWS = "pr_reviews"
    API_CALLS = "api_calls"


@dataclass
class PlanLimits:
    """Resource limits for a marketplace plan."""

    verifications_per_month: int = 50
    ai_analyses_per_month: int = 20
    pr_reviews_per_month: int = 30
    api_calls_per_month: int = 500
    max_repos: int = 3
    max_team_members: int = 1
    private_repos: bool = False
    priority_support: bool = False
    custom_rules: bool = False
    sarif_export: bool = False

    @classmethod
    def for_plan(cls, plan: MarketplacePlan) -> PlanLimits:
        plans = {
            MarketplacePlan.FREE: cls(
                verifications_per_month=50,
                ai_analyses_per_month=20,
                pr_reviews_per_month=30,
                api_calls_per_month=500,
                max_repos=3,
                max_team_members=1,
            ),
            MarketplacePlan.PRO: cls(
                verifications_per_month=2000,
                ai_analyses_per_month=500,
                pr_reviews_per_month=1000,
                api_calls_per_month=10000,
                max_repos=20,
                max_team_members=5,
                private_repos=True,
                custom_rules=True,
                sarif_export=True,
            ),
            MarketplacePlan.TEAM: cls(
                verifications_per_month=10000,
                ai_analyses_per_month=5000,
                pr_reviews_per_month=5000,
                api_calls_per_month=50000,
                max_repos=100,
                max_team_members=50,
                private_repos=True,
                priority_support=True,
                custom_rules=True,
                sarif_export=True,
            ),
            MarketplacePlan.ENTERPRISE: cls(
                verifications_per_month=-1,
                ai_analyses_per_month=-1,
                pr_reviews_per_month=-1,
                api_calls_per_month=-1,
                max_repos=-1,
                max_team_members=-1,
                private_repos=True,
                priority_support=True,
                custom_rules=True,
                sarif_export=True,
            ),
        }
        return plans.get(plan, cls())


@dataclass
class MarketplaceListing:
    """GitHub Marketplace listing metadata."""

    name: str = "CodeVerify"
    slug: str = "codeverify"
    tagline: str = "AI-powered code review with formal verification"
    description: str = (
        "Catch bugs, security vulnerabilities, and logical errors in code—"
        "especially code generated by AI coding assistants. Combines LLM "
        "semantic analysis with Z3 SMT solver formal proofs."
    )
    categories: list[str] = field(
        default_factory=lambda: ["code-review", "security", "code-quality"]
    )
    pricing_model: str = "per-unit"
    plans: list[MarketplacePlan] = field(
        default_factory=lambda: list(MarketplacePlan)
    )
    homepage_url: str = "https://codeverify.dev"
    docs_url: str = "https://docs.codeverify.dev"
    support_url: str = "https://codeverify.dev/support"
    privacy_url: str = "https://codeverify.dev/privacy"
    tos_url: str = "https://codeverify.dev/terms"
    logo_url: str = "https://codeverify.dev/logo.png"
    screenshots: list[str] = field(default_factory=list)


@dataclass
class Installation:
    """A GitHub App installation record."""

    id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    github_installation_id: int = 0
    account_login: str = ""
    account_type: str = "User"  # User or Organization
    plan: MarketplacePlan = MarketplacePlan.FREE
    status: InstallationStatus = InstallationStatus.PENDING
    repos: list[str] = field(default_factory=list)
    onboarding_phase: OnboardingPhase = OnboardingPhase.APP_INSTALLED
    installed_at: datetime = field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    config_generated: bool = False
    workflow_created: bool = False
    baseline_scan_done: bool = False


@dataclass
class UsageRecord:
    """Usage record for a billing period."""

    installation_id: str = ""
    period_start: datetime = field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    metrics: dict[str, int] = field(default_factory=lambda: {
        UsageMetric.VERIFICATIONS.value: 0,
        UsageMetric.AI_ANALYSES.value: 0,
        UsageMetric.PR_REVIEWS.value: 0,
        UsageMetric.API_CALLS.value: 0,
    })

    def increment(self, metric: UsageMetric, count: int = 1) -> None:
        key = metric.value
        self.metrics[key] = self.metrics.get(key, 0) + count


@dataclass
class OnboardingConfig:
    """Generated onboarding configuration for a repo."""

    repo: str = ""
    config_yaml: str = ""
    workflow_yaml: str = ""
    detected_languages: list[str] = field(default_factory=list)
    detected_frameworks: list[str] = field(default_factory=list)
    estimated_first_scan_minutes: int = 5


@dataclass
class InstallationEvent:
    """An event in the installation lifecycle."""

    id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    installation_id: str = ""
    event_type: str = ""
    details: dict[str, Any] = field(default_factory=dict)
    timestamp: datetime = field(
        default_factory=lambda: datetime.now(timezone.utc)
    )


class ConfigAutoGenerator:
    """Generates .codeverify.yml from project analysis."""

    LANGUAGE_MAP: dict[str, list[str]] = {
        ".py": ["python"],
        ".ts": ["typescript"],
        ".tsx": ["typescript"],
        ".js": ["javascript"],
        ".jsx": ["javascript"],
        ".go": ["go"],
        ".java": ["java"],
        ".rs": ["rust"],
        ".c": ["c"],
        ".cpp": ["cpp"],
        ".h": ["c"],
        ".hpp": ["cpp"],
    }

    FRAMEWORK_INDICATORS: dict[str, str] = {
        "requirements.txt": "pip",
        "pyproject.toml": "python-package",
        "package.json": "node",
        "go.mod": "go-module",
        "Cargo.toml": "rust-cargo",
        "pom.xml": "maven",
        "build.gradle": "gradle",
        "Makefile": "make",
    }

    def detect_languages(self, file_paths: list[str]) -> list[str]:
        """Detect languages from file extensions."""
        langs: set[str] = set()
        for path in file_paths:
            for ext, detected in self.LANGUAGE_MAP.items():
                if path.endswith(ext):
                    langs.update(detected)
        return sorted(langs)

    def detect_frameworks(self, file_paths: list[str]) -> list[str]:
        """Detect build frameworks from config files."""
        frameworks: list[str] = []
        for path in file_paths:
            for indicator, framework in self.FRAMEWORK_INDICATORS.items():
                if path.endswith(indicator):
                    frameworks.append(framework)
        return sorted(set(frameworks))

    def generate_config(
        self,
        repo: str,
        file_paths: list[str],
        *,
        strict: bool = False,
    ) -> OnboardingConfig:
        """Generate a .codeverify.yml config for a repository."""
        languages = self.detect_languages(file_paths)
        frameworks = self.detect_frameworks(file_paths)

        checks = ["null_safety", "array_bounds", "integer_overflow", "division_by_zero"]
        if "rust" in languages or "c" in languages or "cpp" in languages:
            checks.extend(["memory_safety", "use_after_free"])
        if "go" in languages:
            checks.append("goroutine_safety")

        thresholds = {
            "critical": 0,
            "high": 0,
            "medium": 2 if strict else 10,
            "low": 5 if strict else 50,
        }

        config_yaml = self._render_config_yaml(languages, checks, thresholds)
        workflow_yaml = self._render_workflow_yaml(repo)

        return OnboardingConfig(
            repo=repo,
            config_yaml=config_yaml,
            workflow_yaml=workflow_yaml,
            detected_languages=languages,
            detected_frameworks=frameworks,
            estimated_first_scan_minutes=max(2, len(file_paths) // 100),
        )

    def _render_config_yaml(
        self,
        languages: list[str],
        checks: list[str],
        thresholds: dict[str, int],
    ) -> str:
        lang_list = "\n".join(f"  - {lang}" for lang in languages)
        check_list = "\n".join(f"    - {c}" for c in checks)
        return (
            f'version: "1"\n\n'
            f"languages:\n{lang_list}\n\n"
            f"verification:\n  enabled: true\n  checks:\n{check_list}\n\n"
            f"ai:\n  enabled: true\n  semantic: true\n  security: true\n\n"
            f"thresholds:\n"
            f"  critical: {thresholds['critical']}\n"
            f"  high: {thresholds['high']}\n"
            f"  medium: {thresholds['medium']}\n"
            f"  low: {thresholds['low']}\n\n"
            f"exclude:\n"
            f'  - "node_modules/**"\n'
            f'  - "venv/**"\n'
            f'  - ".venv/**"\n'
            f'  - "**/__pycache__/**"\n'
        )

    def _render_workflow_yaml(self, repo: str) -> str:
        return (
            "name: CodeVerify\n\n"
            "on:\n"
            "  pull_request:\n"
            "    types: [opened, synchronize, reopened]\n\n"
            "permissions:\n"
            "  contents: read\n"
            "  pull-requests: write\n"
            "  checks: write\n\n"
            "jobs:\n"
            "  verify:\n"
            "    runs-on: ubuntu-latest\n"
            "    steps:\n"
            "      - uses: actions/checkout@v4\n"
            "      - uses: codeverify/codeverify-action@v1\n"
            "        with:\n"
            "          github-token: ${{ secrets.GITHUB_TOKEN }}\n"
        )


class UsageMeter:
    """Tracks and enforces plan usage limits."""

    def __init__(self) -> None:
        self._records: dict[str, UsageRecord] = {}

    def get_usage(self, installation_id: str) -> UsageRecord:
        if installation_id not in self._records:
            self._records[installation_id] = UsageRecord(
                installation_id=installation_id
            )
        return self._records[installation_id]

    def record_usage(
        self,
        installation_id: str,
        metric: UsageMetric,
        count: int = 1,
    ) -> bool:
        """Record usage. Returns True if within limits (limits checked separately)."""
        record = self.get_usage(installation_id)
        record.increment(metric, count)
        logger.info(
            "usage_recorded",
            installation_id=installation_id,
            metric=metric.value,
            count=count,
            total=record.metrics.get(metric.value, 0),
        )
        return True

    def check_limit(
        self,
        installation_id: str,
        metric: UsageMetric,
        limits: PlanLimits,
    ) -> bool:
        """Check if usage is within plan limits. -1 means unlimited."""
        limit_map = {
            UsageMetric.VERIFICATIONS: limits.verifications_per_month,
            UsageMetric.AI_ANALYSES: limits.ai_analyses_per_month,
            UsageMetric.PR_REVIEWS: limits.pr_reviews_per_month,
            UsageMetric.API_CALLS: limits.api_calls_per_month,
        }
        limit = limit_map.get(metric, 0)
        if limit == -1:
            return True
        record = self.get_usage(installation_id)
        current = record.metrics.get(metric.value, 0)
        return current < limit

    def get_remaining(
        self,
        installation_id: str,
        metric: UsageMetric,
        limits: PlanLimits,
    ) -> int:
        """Get remaining usage for a metric. -1 means unlimited."""
        limit_map = {
            UsageMetric.VERIFICATIONS: limits.verifications_per_month,
            UsageMetric.AI_ANALYSES: limits.ai_analyses_per_month,
            UsageMetric.PR_REVIEWS: limits.pr_reviews_per_month,
            UsageMetric.API_CALLS: limits.api_calls_per_month,
        }
        limit = limit_map.get(metric, 0)
        if limit == -1:
            return -1
        record = self.get_usage(installation_id)
        current = record.metrics.get(metric.value, 0)
        return max(0, limit - current)

    def reset_period(self, installation_id: str) -> None:
        """Reset usage for a new billing period."""
        self._records[installation_id] = UsageRecord(
            installation_id=installation_id
        )


class MarketplaceService:
    """Main service for GitHub Marketplace operations."""

    def __init__(self) -> None:
        self._installations: dict[str, Installation] = {}
        self._events: list[InstallationEvent] = []
        self._config_generator = ConfigAutoGenerator()
        self._usage_meter = UsageMeter()
        self._listing = MarketplaceListing()

    @property
    def listing(self) -> MarketplaceListing:
        return self._listing

    @property
    def usage_meter(self) -> UsageMeter:
        return self._usage_meter

    def handle_installation(
        self,
        github_installation_id: int,
        account_login: str,
        account_type: str = "User",
        repos: list[str] | None = None,
        plan: MarketplacePlan = MarketplacePlan.FREE,
    ) -> Installation:
        """Handle a new GitHub App installation."""
        installation = Installation(
            github_installation_id=github_installation_id,
            account_login=account_login,
            account_type=account_type,
            plan=plan,
            status=InstallationStatus.ACTIVE,
            repos=repos or [],
        )
        self._installations[installation.id] = installation
        self._record_event(installation.id, "installed", {
            "account": account_login,
            "plan": plan.value,
            "repo_count": len(installation.repos),
        })
        logger.info(
            "marketplace_installation",
            installation_id=installation.id,
            account=account_login,
            plan=plan.value,
        )
        return installation

    def one_click_onboard(
        self,
        installation_id: str,
        file_paths: list[str],
        *,
        strict: bool = False,
    ) -> OnboardingConfig:
        """Run one-click onboarding for an installation."""
        installation = self._installations.get(installation_id)
        if not installation:
            raise ValueError(f"Installation {installation_id} not found")

        repo = installation.repos[0] if installation.repos else "unknown"
        config = self._config_generator.generate_config(
            repo, file_paths, strict=strict
        )

        installation.config_generated = True
        installation.onboarding_phase = OnboardingPhase.CONFIG_GENERATED
        self._record_event(installation_id, "config_generated", {
            "languages": config.detected_languages,
            "frameworks": config.detected_frameworks,
        })

        installation.workflow_created = True
        installation.onboarding_phase = OnboardingPhase.WORKFLOW_CREATED
        self._record_event(installation_id, "workflow_created", {})

        installation.onboarding_phase = OnboardingPhase.BASELINE_SCAN_QUEUED
        self._record_event(installation_id, "baseline_scan_queued", {
            "estimated_minutes": config.estimated_first_scan_minutes,
        })

        return config

    def complete_onboarding(self, installation_id: str) -> bool:
        """Mark onboarding as complete after baseline scan."""
        installation = self._installations.get(installation_id)
        if not installation:
            return False
        installation.onboarding_phase = OnboardingPhase.ONBOARDING_COMPLETE
        installation.baseline_scan_done = True
        self._record_event(installation_id, "onboarding_complete", {})
        return True

    def change_plan(
        self,
        installation_id: str,
        new_plan: MarketplacePlan,
    ) -> bool:
        """Handle a plan change (upgrade/downgrade)."""
        installation = self._installations.get(installation_id)
        if not installation:
            return False
        old_plan = installation.plan
        installation.plan = new_plan
        self._record_event(installation_id, "plan_changed", {
            "old_plan": old_plan.value,
            "new_plan": new_plan.value,
        })
        logger.info(
            "plan_changed",
            installation_id=installation_id,
            old_plan=old_plan.value,
            new_plan=new_plan.value,
        )
        return True

    def suspend_installation(self, installation_id: str) -> bool:
        """Suspend an installation."""
        installation = self._installations.get(installation_id)
        if not installation:
            return False
        installation.status = InstallationStatus.SUSPENDED
        self._record_event(installation_id, "suspended", {})
        return True

    def uninstall(self, installation_id: str) -> bool:
        """Handle uninstallation."""
        installation = self._installations.get(installation_id)
        if not installation:
            return False
        installation.status = InstallationStatus.UNINSTALLED
        self._record_event(installation_id, "uninstalled", {})
        return True

    def get_installation(self, installation_id: str) -> Installation | None:
        return self._installations.get(installation_id)

    def list_active_installations(self) -> list[Installation]:
        return [
            i for i in self._installations.values()
            if i.status == InstallationStatus.ACTIVE
        ]

    def get_installation_events(
        self, installation_id: str
    ) -> list[InstallationEvent]:
        return [e for e in self._events if e.installation_id == installation_id]

    def get_analytics(self) -> dict[str, Any]:
        """Get aggregate installation analytics."""
        active = self.list_active_installations()
        plan_counts: dict[str, int] = defaultdict(int)
        for inst in active:
            plan_counts[inst.plan.value] += 1

        return {
            "total_installations": len(self._installations),
            "active_installations": len(active),
            "plan_distribution": dict(plan_counts),
            "total_repos": sum(len(i.repos) for i in active),
            "onboarding_complete": sum(
                1 for i in active if i.baseline_scan_done
            ),
        }

    def _record_event(
        self,
        installation_id: str,
        event_type: str,
        details: dict[str, Any],
    ) -> None:
        self._events.append(InstallationEvent(
            installation_id=installation_id,
            event_type=event_type,
            details=details,
        ))


# ─── Singleton Access ──────────────────────────────────────────────────


_marketplace_instance: MarketplaceService | None = None


def get_marketplace_service() -> MarketplaceService:
    """Get or create the singleton MarketplaceService."""
    global _marketplace_instance
    if _marketplace_instance is None:
        _marketplace_instance = MarketplaceService()
    return _marketplace_instance


def reset_marketplace_service() -> None:
    """Reset the singleton (for testing)."""
    global _marketplace_instance
    _marketplace_instance = None
