"""CodeVerify Verifier - Formal verification using Z3 SMT solver."""

from codeverify_verifier.z3_verifier import Z3Verifier
from codeverify_verifier.conditions import (
    generate_null_check,
    generate_bounds_check,
    generate_overflow_check,
)
from codeverify_verifier.debugger import (
    VerificationDebugger,
    DebugStep,
    DebugSession,
    StepStatus,
)
from codeverify_verifier.reachability import (
    CallEdge,
    CallGraphBuilder,
    CodeNode,
    ReachabilityAnalyzer,
    ReachabilityReport,
    ReachabilityResult,
    ReachabilityStatus,
    Vulnerability,
    VulnerabilityScanner,
    VulnerabilityType,
    create_cve_vulnerability,
)
from codeverify_verifier.runtime_probes import (
    MonitorMode,
    ProbeConfig,
    ProbeGenerator,
    ProbeType,
    RuntimeMonitor,
    RuntimeSpec,
    RuntimeVerificationReport,
    SpecViolation,
    SpecViolationEvent,
    check,
    create_monitor,
    runtime_invariant,
    runtime_postcondition,
    runtime_precondition,
)
from codeverify_verifier.counterexample_playground import (
    Counterexample,
    CounterexampleVisualizer,
    ExecutionStep,
    ExecutionTrace,
    PlaygroundAPI,
    PlaygroundEngine,
    PlaygroundSession,
    StepType,
    TraceGenerator,
    Variable,
    VariableType,
    Z3ModelParser,
    create_playground,
)
from codeverify_verifier.prometheus_metrics import (
    Counter,
    Gauge,
    Histogram,
    MetricsExporter,
    MetricsIntegration,
    MetricsServer,
    RuntimeProbeMetrics,
    Summary,
    format_json,
    format_prometheus,
    get_global_metrics,
    observe_spec_check,
    reset_global_metrics,
)

__all__ = [
    "Z3Verifier",
    "generate_null_check",
    "generate_bounds_check",
    "generate_overflow_check",
    # Debugger
    "VerificationDebugger",
    "DebugStep",
    "DebugSession",
    "StepStatus",
    # Reachability Analysis
    "CallEdge",
    "CallGraphBuilder",
    "CodeNode",
    "ReachabilityAnalyzer",
    "ReachabilityReport",
    "ReachabilityResult",
    "ReachabilityStatus",
    "Vulnerability",
    "VulnerabilityScanner",
    "VulnerabilityType",
    "create_cve_vulnerability",
    # Runtime Verification Probes
    "MonitorMode",
    "ProbeConfig",
    "ProbeGenerator",
    "ProbeType",
    "RuntimeMonitor",
    "RuntimeSpec",
    "RuntimeVerificationReport",
    "SpecViolation",
    "SpecViolationEvent",
    "check",
    "create_monitor",
    "runtime_invariant",
    "runtime_postcondition",
    "runtime_precondition",
    # Counterexample Playground
    "Counterexample",
    "CounterexampleVisualizer",
    "ExecutionStep",
    "ExecutionTrace",
    "PlaygroundAPI",
    "PlaygroundEngine",
    "PlaygroundSession",
    "StepType",
    "TraceGenerator",
    "Variable",
    "VariableType",
    "Z3ModelParser",
    "create_playground",
    # Prometheus Metrics
    "Counter",
    "Gauge",
    "Histogram",
    "MetricsExporter",
    "MetricsIntegration",
    "MetricsServer",
    "RuntimeProbeMetrics",
    "Summary",
    "format_json",
    "format_prometheus",
    "get_global_metrics",
    "observe_spec_check",
    "reset_global_metrics",
]
