/**
 * Pure analysis/statistics helpers used by PasteInterceptionProvider.
 *
 * PasteInterceptionProvider's constructor creates VS Code status bar items,
 * event emitters, etc. at construction time, so it can only be exercised
 * inside the VS Code extension host. The functions below contain the actual
 * decision logic (code detection heuristics, risk-level derivation, model
 * detection, recommendations, rolling statistics) and have no `vscode`
 * dependency, so they live in this separate module and can be unit tested
 * directly with Node's built-in test runner. `pasteInterceptionProvider.ts`
 * imports and delegates to these functions to avoid duplicating the logic.
 */

import type { Finding, TrustScore } from './client';
import type { InterceptionStatistics, PasteAnalysisResult, PasteDecision } from './providers/pasteInterceptionProvider';

/**
 * Check if pasted text looks like code (vs. plain text/prose).
 */
export function looksLikeCode(text: string, languageId: string): boolean {
    const lines = text.split('\n');

    // Too few lines
    if (lines.length < 2) return false;

    // Check for common code patterns
    const codePatterns = [
        /^\s*(def|function|class|const|let|var|import|from|async|export)\s/m,
        /[{}[\]();]/,
        /^\s*(if|for|while|try|return)\s/m,
        /=>/,
        /:\s*(int|str|float|bool|string|number|void)\b/,
        /^\s*#\s*\w+/m,  // Comments
        /\/\//,  // JS comments
        /^\s*@\w+/m,  // Decorators
    ];

    let patternMatches = 0;
    for (const pattern of codePatterns) {
        if (pattern.test(text)) {
            patternMatches++;
        }
    }

    return patternMatches >= 2;
}

/**
 * Determine the risk level for an analyzed paste, preferring the trust
 * score's own `risk_level` (as computed by the server or local trust-score
 * fallback) and only deriving one from the raw score if that's absent.
 */
export function determineRiskLevel(trustScore: TrustScore): 'low' | 'medium' | 'high' | 'critical' {
    const score = trustScore.score || 0;
    const riskLevel = trustScore.risk_level;

    if (riskLevel) {
        return riskLevel as 'low' | 'medium' | 'high' | 'critical';
    }

    if (score >= 80) return 'low';
    if (score >= 60) return 'medium';
    if (score >= 40) return 'high';
    return 'critical';
}

/**
 * Best-effort detection of which AI model/tool likely produced this code,
 * based on telltale comment patterns.
 */
export function detectModel(code: string, _trustScore: TrustScore): string {
    // Check for model-specific patterns
    const patterns: [RegExp, string][] = [
        [/# Copilot|GitHub Copilot/i, 'GitHub Copilot'],
        [/```python|Here's (a|an|the)/i, 'ChatGPT'],
        [/I'll (create|implement)/i, 'Claude'],
        [/Generated by|Created with/i, 'AI Assistant'],
    ];

    for (const [pattern, model] of patterns) {
        if (pattern.test(code)) {
            return model;
        }
    }

    return 'unknown';
}

/**
 * Build user-facing recommendations from a trust score and findings.
 */
export function generateRecommendations(trustScore: TrustScore, findings: Finding[]): string[] {
    const recommendations: string[] = [];

    if (trustScore.ai_probability && trustScore.ai_probability > 70) {
        recommendations.push('Manual review recommended for AI-generated code');
    }

    if (findings.some(f => f.severity === 'critical')) {
        recommendations.push('Critical issues detected - fix before committing');
    }

    if (findings.some(f => f.category === 'security')) {
        recommendations.push('Security review required');
    }

    if ((trustScore.score || 0) < 60) {
        recommendations.push('Consider running formal verification');
    }

    if (recommendations.length === 0) {
        recommendations.push('Code looks good, but manual review is still recommended');
    }

    return recommendations;
}

/**
 * Conservative trust score used when the real one can't be computed
 * (e.g. both the API call and local fallback failed).
 */
export function getDefaultTrustScore(): TrustScore {
    return {
        score: 50,
        ai_probability: 0,
        risk_level: 'medium',
        complexity_score: 0,
        pattern_score: 0,
        quality_score: 0,
        verification_score: 0,
        factors: {},
    };
}

/**
 * Fresh, zeroed-out interception statistics.
 */
export function initializeStatistics(): InterceptionStatistics {
    return {
        totalInterceptions: 0,
        aiDetectedCount: 0,
        acceptedCount: 0,
        rejectedCount: 0,
        modifiedCount: 0,
        averageTrustScore: 0,
        averageAnalysisTimeMs: 0,
    };
}

/**
 * Return updated statistics (rolling averages included) after a new paste
 * analysis result. Pure/immutable: does not mutate `stats`.
 */
export function updatePasteStatistics(
    stats: InterceptionStatistics,
    result: PasteAnalysisResult
): InterceptionStatistics {
    const totalInterceptions = stats.totalInterceptions + 1;
    const aiDetectedCount = stats.aiDetectedCount + (result.isAiGenerated ? 1 : 0);

    // Rolling average
    const n = totalInterceptions;
    const averageTrustScore = (stats.averageTrustScore * (n - 1) + result.trustScore) / n;
    const averageAnalysisTimeMs = (stats.averageAnalysisTimeMs * (n - 1) + result.analysisTimeMs) / n;

    return {
        ...stats,
        totalInterceptions,
        aiDetectedCount,
        averageTrustScore,
        averageAnalysisTimeMs,
    };
}

/**
 * Return updated statistics after a user decision (accept/reject/modify).
 * Pure/immutable: does not mutate `stats`.
 */
export function updateDecisionStatistics(
    stats: InterceptionStatistics,
    decision: PasteDecision
): InterceptionStatistics {
    switch (decision) {
        case 'accept':
        case 'accept_with_review':
            return { ...stats, acceptedCount: stats.acceptedCount + 1 };
        case 'reject':
            return { ...stats, rejectedCount: stats.rejectedCount + 1 };
        case 'modify':
            return { ...stats, modifiedCount: stats.modifiedCount + 1 };
        default:
            return stats;
    }
}
