"""AI Code Interceptor — Detects and risk-scores AI-generated code in real-time.

Intercepts code completions from AI assistants (Copilot, Cursor, Windsurf) via
LSP, applies risk scoring, and provides inline warnings before code is accepted.
"""

import hashlib
import re
import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Any

import structlog

logger = structlog.get_logger()


class RiskLevel(str, Enum):
    """Risk classification for intercepted code."""

    SAFE = "safe"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class AISource(str, Enum):
    """Detected AI assistant source."""

    COPILOT = "copilot"
    CURSOR = "cursor"
    WINDSURF = "windsurf"
    TABNINE = "tabnine"
    CODEWHISPERER = "codewhisperer"
    UNKNOWN_AI = "unknown_ai"
    HUMAN = "human"


@dataclass
class InterceptionConfig:
    """Configuration for AI code interception."""

    enabled: bool = True
    min_insertion_length: int = 20
    risk_threshold: RiskLevel = RiskLevel.MEDIUM
    debounce_ms: int = 500
    cache_max_size: int = 1000
    check_patterns: bool = True
    check_security: bool = True
    check_correctness: bool = True


@dataclass
class AIDetectionSignal:
    """A signal that code may be AI-generated."""

    name: str
    confidence: float  # 0.0-1.0
    evidence: str


@dataclass
class RiskFactor:
    """A specific risk identified in the code."""

    category: str
    severity: RiskLevel
    description: str
    line: int | None = None
    fix_suggestion: str | None = None


@dataclass
class InterceptionResult:
    """Result of intercepting and analyzing a code insertion."""

    code_hash: str
    source: AISource
    ai_confidence: float
    risk_level: RiskLevel
    risk_score: float  # 0-100
    risk_factors: list[RiskFactor] = field(default_factory=list)
    detection_signals: list[AIDetectionSignal] = field(default_factory=list)
    analysis_ms: float = 0
    cached: bool = False

    @property
    def should_warn(self) -> bool:
        risk_order = list(RiskLevel)
        return risk_order.index(self.risk_level) >= risk_order.index(RiskLevel.MEDIUM)

    def to_dict(self) -> dict[str, Any]:
        return {
            "source": self.source.value,
            "ai_confidence": self.ai_confidence,
            "risk_level": self.risk_level.value,
            "risk_score": self.risk_score,
            "risk_factors": [
                {
                    "category": f.category,
                    "severity": f.severity.value,
                    "description": f.description,
                    "fix_suggestion": f.fix_suggestion,
                }
                for f in self.risk_factors
            ],
            "analysis_ms": self.analysis_ms,
        }


class AIDetector:
    """Detects whether code was generated by an AI assistant.

    Uses heuristic signals to estimate AI authorship probability.
    """

    # Patterns commonly seen in AI-generated code
    AI_COMMENT_PATTERNS = [
        re.compile(r"#\s*Generated by", re.IGNORECASE),
        re.compile(r"//\s*Auto-generated", re.IGNORECASE),
        re.compile(r"#\s*TODO:?\s*(?:implement|add|fix)", re.IGNORECASE),
        re.compile(r"#\s*Note:?\s*This (?:function|method|class)", re.IGNORECASE),
    ]

    # AI tends to generate overly verbose variable names
    VERBOSE_NAME_PATTERN = re.compile(r"\b\w{25,}\b")

    # AI often generates placeholder/example values
    PLACEHOLDER_PATTERNS = [
        re.compile(r"example\.com|foo|bar|baz|lorem|ipsum"),
        re.compile(r"your[_-]?(?:api[_-]?key|token|secret)", re.IGNORECASE),
    ]

    def detect(
        self, code: str, context: dict[str, Any] | None = None
    ) -> tuple[AISource, float, list[AIDetectionSignal]]:
        """Detect if code is AI-generated and estimate confidence."""
        signals: list[AIDetectionSignal] = []
        context = context or {}

        # Check IDE metadata if available
        if context.get("completion_source") == "copilot":
            signals.append(AIDetectionSignal("ide_metadata", 0.95, "Copilot completion event"))
            return AISource.COPILOT, 0.95, signals

        if context.get("completion_source") == "cursor":
            signals.append(AIDetectionSignal("ide_metadata", 0.95, "Cursor completion event"))
            return AISource.CURSOR, 0.95, signals

        # Heuristic detection
        for pattern in self.AI_COMMENT_PATTERNS:
            if pattern.search(code):
                signals.append(AIDetectionSignal("ai_comment", 0.7, f"Pattern: {pattern.pattern}"))

        if self.VERBOSE_NAME_PATTERN.search(code):
            signals.append(AIDetectionSignal("verbose_names", 0.3, "Unusually long identifiers"))

        for pattern in self.PLACEHOLDER_PATTERNS:
            if pattern.search(code):
                signals.append(
                    AIDetectionSignal("placeholder_values", 0.4, f"Pattern: {pattern.pattern}")
                )

        # Large multi-line insertions are more likely AI
        line_count = code.count("\n") + 1
        if line_count > 15:
            signals.append(
                AIDetectionSignal("large_insertion", 0.5, f"{line_count} lines inserted at once")
            )
        elif line_count > 30:
            signals.append(AIDetectionSignal("very_large_insertion", 0.7, f"{line_count} lines"))

        # Uniform formatting is an AI signal
        lines = code.strip().split("\n")
        if len(lines) > 5:
            indent_pattern = re.compile(r"^(\s*)")
            indents = [len(indent_pattern.match(line).group(1)) for line in lines if line.strip()]
            if indents and len(set(indents)) <= 3:
                signals.append(
                    AIDetectionSignal("uniform_indent", 0.2, "Very consistent indentation")
                )

        if not signals:
            return AISource.HUMAN, 0.1, signals

        confidence = min(1.0, sum(s.confidence for s in signals) / max(len(signals), 1))
        source = AISource.UNKNOWN_AI if confidence > 0.5 else AISource.HUMAN
        return source, confidence, signals


class RiskScorer:
    """Scores risk of code insertions using pattern-based security checks."""

    SECURITY_PATTERNS = [
        (
            re.compile(r"eval\s*\("),
            "code_injection",
            RiskLevel.CRITICAL,
            "eval() allows arbitrary code execution",
        ),
        (
            re.compile(r"exec\s*\("),
            "code_injection",
            RiskLevel.CRITICAL,
            "exec() allows arbitrary code execution",
        ),
        (
            re.compile(r"subprocess\.(?:call|run|Popen)\s*\(.*shell\s*=\s*True"),
            "command_injection",
            RiskLevel.CRITICAL,
            "Shell=True enables command injection",
        ),
        (
            re.compile(r"os\.system\s*\("),
            "command_injection",
            RiskLevel.HIGH,
            "os.system() is vulnerable to injection",
        ),
        (
            re.compile(r"__import__\s*\("),
            "code_injection",
            RiskLevel.HIGH,
            "Dynamic import can load malicious modules",
        ),
        (
            re.compile(r"pickle\.loads?\s*\("),
            "deserialization",
            RiskLevel.HIGH,
            "pickle deserialization is unsafe with untrusted data",
        ),
        (
            re.compile(r"yaml\.load\s*\((?!.*Loader)"),
            "deserialization",
            RiskLevel.HIGH,
            "yaml.load without SafeLoader is unsafe",
        ),
        (
            re.compile(r"SELECT\s+.*\+\s*[\w\"']|f[\"'].*SELECT.*\{"),
            "sql_injection",
            RiskLevel.HIGH,
            "String concatenation in SQL query",
        ),
        (
            re.compile(r"password\s*=\s*[\"'][^\"']+[\"']"),
            "hardcoded_secret",
            RiskLevel.HIGH,
            "Hardcoded password detected",
        ),
        (
            re.compile(r"(?:api[_-]?key|secret|token)\s*=\s*[\"'][A-Za-z0-9+/=]{16,}"),
            "hardcoded_secret",
            RiskLevel.CRITICAL,
            "Hardcoded secret/token detected",
        ),
        (
            re.compile(r"verify\s*=\s*False"),
            "tls_bypass",
            RiskLevel.MEDIUM,
            "TLS verification disabled",
        ),
        (
            re.compile(r"CORS\(.*origins?\s*=\s*[\"']\*[\"']"),
            "cors_misconfiguration",
            RiskLevel.MEDIUM,
            "CORS allows all origins",
        ),
    ]

    CORRECTNESS_PATTERNS = [
        (
            re.compile(r"except\s*:\s*$", re.MULTILINE),
            "bare_except",
            RiskLevel.LOW,
            "Bare except catches all exceptions including SystemExit",
        ),
        (
            re.compile(r"except\s+Exception\s*:\s*\n\s*pass"),
            "swallowed_exception",
            RiskLevel.MEDIUM,
            "Exception silently swallowed",
        ),
        (
            re.compile(r"\.split\(\)[^\]]*\[\d+\]"),
            "index_error",
            RiskLevel.LOW,
            "Unchecked index access on split result",
        ),
        (
            re.compile(r"type\(\w+\)\s*=="),
            "type_comparison",
            RiskLevel.LOW,
            "Use isinstance() instead of type() ==",
        ),
    ]

    def score(
        self, code: str, _language: str = "python"
    ) -> tuple[float, RiskLevel, list[RiskFactor]]:
        """Score the risk of a code insertion. Returns (score, level, factors)."""
        factors: list[RiskFactor] = []

        for pattern, category, severity, desc in self.SECURITY_PATTERNS:
            for match in pattern.finditer(code):
                line_num = code[: match.start()].count("\n") + 1
                factors.append(
                    RiskFactor(
                        category=category,
                        severity=severity,
                        description=desc,
                        line=line_num,
                        fix_suggestion=self._suggest_fix(category),
                    )
                )

        for pattern, category, severity, desc in self.CORRECTNESS_PATTERNS:
            for match in pattern.finditer(code):
                line_num = code[: match.start()].count("\n") + 1
                factors.append(
                    RiskFactor(
                        category=category,
                        severity=severity,
                        description=desc,
                        line=line_num,
                    )
                )

        # Calculate score
        severity_weights = {
            RiskLevel.CRITICAL: 30,
            RiskLevel.HIGH: 15,
            RiskLevel.MEDIUM: 5,
            RiskLevel.LOW: 1,
        }
        score = min(100.0, sum(severity_weights.get(f.severity, 0) for f in factors))

        if score >= 50:
            level = RiskLevel.CRITICAL
        elif score >= 25:
            level = RiskLevel.HIGH
        elif score >= 10:
            level = RiskLevel.MEDIUM
        elif score > 0:
            level = RiskLevel.LOW
        else:
            level = RiskLevel.SAFE

        return score, level, factors

    def _suggest_fix(self, category: str) -> str | None:
        fixes = {
            "code_injection": "Use ast.literal_eval() or parameterized alternatives",
            "command_injection": "Use subprocess with shell=False and argument list",
            "sql_injection": "Use parameterized queries with placeholders",
            "hardcoded_secret": "Use environment variables or a secrets manager",
            "deserialization": "Use json or safe loaders for untrusted data",
            "tls_bypass": "Enable TLS verification (verify=True)",
            "cors_misconfiguration": "Specify allowed origins explicitly",
        }
        return fixes.get(category)


class AICodeInterceptor:
    """Main interceptor that combines AI detection with risk scoring.

    Designed to be called from the LSP server on code insertion events.

    Example:
        >>> interceptor = AICodeInterceptor()
        >>> result = interceptor.intercept(
        ...     code="import os; os.system(user_input)",
        ...     language="python",
        ...     context={"completion_source": "copilot"},
        ... )
        >>> result.risk_level
        RiskLevel.HIGH
    """

    def __init__(self, config: InterceptionConfig | None = None) -> None:
        self.config = config or InterceptionConfig()
        self._detector = AIDetector()
        self._scorer = RiskScorer()
        self._cache: dict[str, InterceptionResult] = {}

    def intercept(
        self,
        code: str,
        language: str = "python",
        context: dict[str, Any] | None = None,
    ) -> InterceptionResult:
        """Intercept a code insertion and return risk assessment."""
        if not self.config.enabled:
            return InterceptionResult(
                code_hash="",
                source=AISource.HUMAN,
                ai_confidence=0.0,
                risk_level=RiskLevel.SAFE,
                risk_score=0.0,
            )

        start = time.time()
        code_hash = hashlib.sha256(code.encode()).hexdigest()[:16]

        # Check cache
        if code_hash in self._cache:
            cached = self._cache[code_hash]
            cached.cached = True
            return cached

        # Skip very short insertions
        if len(code.strip()) < self.config.min_insertion_length:
            return InterceptionResult(
                code_hash=code_hash,
                source=AISource.HUMAN,
                ai_confidence=0.0,
                risk_level=RiskLevel.SAFE,
                risk_score=0.0,
                analysis_ms=(time.time() - start) * 1000,
            )

        # Detect AI source
        source, ai_confidence, signals = self._detector.detect(code, context)

        # Score risk
        risk_score, risk_level, risk_factors = self._scorer.score(code, language)

        # Boost risk if AI-generated (AI code gets more scrutiny)
        if ai_confidence > 0.5 and risk_score > 0:
            risk_score = min(100.0, risk_score * 1.3)
            if risk_score >= 50:
                risk_level = RiskLevel.CRITICAL
            elif risk_score >= 25:
                risk_level = RiskLevel.HIGH

        result = InterceptionResult(
            code_hash=code_hash,
            source=source,
            ai_confidence=ai_confidence,
            risk_level=risk_level,
            risk_score=risk_score,
            risk_factors=risk_factors,
            detection_signals=signals,
            analysis_ms=(time.time() - start) * 1000,
        )

        # Cache result
        if len(self._cache) >= self.config.cache_max_size:
            oldest = next(iter(self._cache))
            del self._cache[oldest]
        self._cache[code_hash] = result

        logger.info(
            "Code interception complete",
            source=source.value,
            ai_confidence=ai_confidence,
            risk_level=risk_level.value,
            risk_score=risk_score,
            factors=len(risk_factors),
        )

        return result

    def clear_cache(self) -> None:
        self._cache.clear()

    def get_stats(self) -> dict[str, Any]:
        return {
            "cache_size": len(self._cache),
            "config": {
                "enabled": self.config.enabled,
                "risk_threshold": self.config.risk_threshold.value,
                "debounce_ms": self.config.debounce_ms,
            },
        }
